server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-db-instance.c6k558zbt29v.us-east-1.rds.amazonaws.com:5432/postgres
    username: techchallenge
    password: 2I5d3~yiPfab9hr>z
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

aws:
  region: us-east-1
  accessKey: ASIAVG2S5CWJ2DP2YUL7
  secretKey: hmTcqGcJwH3yFrYL7GN2uSBOMyRCTHQd8y/4NGJn
  sessionToken: IQoJb3JpZ2luX2VjEKr//////////wEaCXVzLXdlc3QtMiJHMEUCIFAkEdpW2dUTRNv2zadEW1fw3Q6qEHXnrmsrUCoH46LXAiEAurxEm4Q5jCMgjUj+t+r37brQCl72PD2NAJwfOPj3VrUqrQIIIxABGgwzNTgyNjY3NzA4MzUiDJCqUHKoJ0q27exQZCqKAsleZlxDSIIUiODDpV2uDJcgzxGCteDC9n1nm0qkVUfRJ1QzaPP4wRJ0E57pPoiXBhygN9ditmrr0tEjd8fOjGemXBcnVEMU7eLtYAnYnuYGkcGYHI6Wiezu8lUXl/RF634VyYcqwR0KPXkMz/m7lwdu3k/TXsvHnwh6UlWvOjbMouhkhx10U5xRD8NiHacV45Ri8wzWwF1P0tod6qlpFYgBjlJ3bBG0xPad/xsaE0awjqc1leLWMqIu3dcDVm+OJzXoWC8ra6xOKVqcCzYrTxgZfizXWRGShAmiFzzjODJCglw5nJ2GIfigHWomkC0SBaUF5JwS9xR8j3u0/R6QajLJF6O7qFRRv1ijMJ3iqrIGOp0Bi0YJzr0VjbHlZg1Fsq1ayGMmtwCGGGEiY5gPDiX3hRoyoCRhc5o99mG7i/o4Iu6E0XpNHSArNzwDWqCu+JTd/XDp4wseUPUmb9FIipoD3btlguW+HdLW0LAfNNflJzNmVLCbU1men8j/U8z4iguOKOuAEoEPTbZ+5uVWFAcMESjahRxekgD/OkG7NKeDe5thjz5xpUmXLRrEK2LNpA==
  sqs:
    endpoint: https://sqs.us-east-1.amazonaws.com
    queue:
      payment:
        endpoint: https://sqs.us-east-1.amazonaws.com/358266770835/tech_challenge_pagamento
